site_name: 'Andrew Lohman'
name: Andrew Lohman
markdown: rdiscount
rdiscount:
    extensions: [smart]
permalink: /:categories/:title.html
paginate: 6
baseurl: /andrewlohman


# name: Andrew Lohman
# markdown: redcarpet
# pygments: true
# baseurl: /andrewlohman