site_name: 'Andrew Lohman'
name: Andrew Lohman
markdown: rdiscount
rdiscount:
    extensions: [smart]
# permalink: /articles/:title
paginate: 6
baseurl: /andrewlohman


# name: Andrew Lohman
# markdown: redcarpet
# pygments: true
# baseurl: /andrewlohman